In [1]:
import pandas as pd
import re
import numpy as np
# from deep_translator import GoogleTranslator

In [40]:
pd.set_option('display.max_rows', None)

In [21]:
rassereno_path = '/Users/emma/projects/cognoscolab/rassereno'
math_ma_llm = '/Users/emma/projects/cognoscolab/math_anxiety_LLMs'

## MAS-IT dataframes merge

In [4]:
mas_it_2023 = pd.read_csv(f'{math_ma_llm}/out/formatting/humans_2023/mas_it_2023_humans.csv')
mas_it_humans_2024 = pd.read_csv(f'{math_ma_llm}/out/formatting/humans_2024/mas_it_2024_humans.csv')
mas_it_BA_2024 = pd.read_csv(f'{rassereno_path}/out/formatting/psychology_BA_2024/mas_it_2024.csv')
mas_it_2025 = pd.read_csv(f'{rassereno_path}/out/formatting/all_students_2025/mas_it_2025.csv')

In [5]:
mas_it_university_2025 = mas_it_2025[
    mas_it_2025['participant_id'].str.startswith('interfacce') |
    mas_it_2025['participant_id'].str.startswith('fisica')
].reset_index(drop=True)

mas_it_liceo_2025 = mas_it_2025[
    mas_it_2025['participant_id'].str.startswith('liceo')
].reset_index(drop=True)

mas_it_liceo_2025.to_csv(f'{rassereno_path}/out/formatting/liceo_2025/mas_it_liceo_2025.csv', index=False)

In [6]:
# get the column names of the 2025 dataset
cols_2025 = mas_it_university_2025.columns

# restrict all dataframes to those columns before concatenation
dfs = [
    mas_it_humans_2024[cols_2025.intersection(mas_it_humans_2024.columns)],
    mas_it_2023[cols_2025.intersection(mas_it_2023.columns)],
    mas_it_BA_2024[cols_2025.intersection(mas_it_BA_2024.columns)],
    mas_it_university_2025[cols_2025]
]

# concatenate them
all_universities_mas_it = pd.concat(dfs, ignore_index=True)
all_universities_mas_it.to_csv(f'{rassereno_path}/out/formatting/all_university_students/mas_it_all_universities.csv', index=False)

## Associations and Valence dataframes merge

In [7]:
associations_valence_2023 = pd.read_csv(f'{math_ma_llm}/out/formatting/humans_2023/associations_valence_2023_humans.csv')
associations_valence_2024 = pd.read_csv(f'{math_ma_llm}/out/formatting/humans_2024/associations_valence_2024_humans.csv')
associations_valence_BA_2024 = pd.read_csv(f'{rassereno_path}/out/formatting/psychology_BA_2024/associations_valence_2024.csv')
associations_valence_2025 = pd.read_csv(f'{rassereno_path}/out/formatting/all_students_2025/associations_valence_task_2025.csv')

In [8]:
associations_valence_university_2025 = associations_valence_2025[
    associations_valence_2025['participant_id'].str.startswith('interfacce') |
    associations_valence_2025['participant_id'].str.startswith('fisica')
]
associations_valence_liceo_2025 = associations_valence_2025[
    associations_valence_2025['participant_id'].str.startswith('liceo')
]
associations_valence_liceo_2025.to_csv(f'{rassereno_path}/out/formatting/liceo_2025/associations_valence_liceo_2025.csv', index=False)

In [ ]:
all_universities_associations_valence = pd.concat([associations_valence_2024, associations_valence_2023, associations_valence_BA_2024, associations_valence_university_2025], ignore_index=True)

all_universities_associations_valence.to_csv(f'{rassereno_path}/out/formatting/all_university_students/associations_valence_all_universities.csv', index=False)

## Common words of multiple datasets

In [10]:
common_words_university = list(set(associations_valence_2024['cue_word']) & set(associations_valence_2023['cue_word']) & set(associations_valence_BA_2024['cue_word']) & set(associations_valence_university_2025['cue_word']))

print(f'Common word of all university subgroups: {common_words_university}')

Common word of all university subgroups: ['esame', 'fisica', 'sfida', 'equazione', 'matematica', 'ansia', 'statistica']

In [60]:
gpt_4o_associations_valence = pd.read_csv(f'{math_ma_llm}/out/formatting/gpt_4o/associations_valence_gpt_4o.csv')

In [12]:
list(set(associations_valence_liceo_2025['cue_word']) & set(all_universities_associations_valence['cue_word']) & set(gpt_4o_associations_valence['cue_word']))

['esame',
 'innovazione',
 'fisica',
 'sfida',
 'equazione',
 'benessere',
 'scienza',
 'ansia',
 'matematica',
 'informatica',
 'statistica',
 'scienziato']

In [54]:
def cue_word_extraction(file):
    data = open(file).readlines()

    pairs = [re.findall(r'"([^"]+)"', line) for line in data]

    df = pd.DataFrame(pairs, columns=['association_0', 'association_1'])

    counts = df['association_0'].value_counts()

    cue_words = counts[:len(counts) // 2]

    cue_words_list = cue_words.index.tolist()

    return df, cue_words_list

In [55]:
experts_df_unfiltered, cue_words_experts = cue_word_extraction('/Users/emma/Desktop/data_2021/Experts_unfiltered.txt')

In [59]:
cue_words_experts

['science',
 'university',
 'system',
 'mathematics',
 'physics',
 'art',
 'school',
 'chemistry',
 'life',
 'complex',
 'conference',
 'network',
 'market',
 'analysis',
 'loop',
 'biology',
 'electricity',
 'solid',
 'language',
 'brain',
 'statistics',
 'word',
 'ants',
 'chaos',
 'cloud',
 'scientific',
 'theory',
 'studies',
 'draw',
 'dna',
 'degree',
 'evolution',
 'metal',
 'integral',
 'failure',
 'individual',
 'derivative',
 'element',
 'teaching',
 'model',
 'transistor',
 'force',
 'hub',
 'attractor',
 'theorem',
 'liquid',
 'flow',
 'geography',
 'reasoning',
 'prisoner',
 'geometry',
 'mathematician',
 'character',
 'spike',
 'water',
 'period',
 'health',
 'teacher',
 'instrument',
 'probability',
 'cell',
 'matrix',
 'state',
 'magnetism',
 'approximation',
 'island',
 'curricula',
 'link',
 'cycle',
 'tool',
 'computer',
 'suggestion',
 'saddle',
 'metric',
 'discovery',
 'biosphere',
 'mark',
 'place',
 'emergence',
 'charge',
 'star',
 'flower',
 'town',
 'heat',
 'trigonometry',
 'wellbeing',
 'heart',
 'logistics',
 'chromosome',
 'ecosystem',
 'acquisition',
 'skin',
 'selection',
 'business',
 'application',
 'graph',
 'dilemma',
 'doctorate',
 'organisation',
 'cultural',
 'author',
 'herb',
 'study',
 'fire',
 'writer',
 'logic',
 'edge',
 'telescope',
 'polygon',
 'biologist',
 'coefficient',
 'level',
 'allowance',
 'spring',
 'constant',
 'person',
 'regression',
 'decompose',
 'control',
 'prey',
 'relativity',
 'diode',
 'hole',
 'equation',
 'situation',
 'rational',
 'light',
 'organism',
 'lab',
 'synthesise',
 'combination',
 'fragility',
 'friction',
 'determinism',
 'pandemics',
 'chemicals',
 'interaction',
 'agreement',
 'plot',
 'expansion',
 'student',
 'change',
 'point',
 'syllabus',
 'plane',
 'book',
 'traffic',
 'discharge',
 'experiment',
 'medication',
 'function',
 'pattern',
 'gas',
 'plant',
 'land_rover',
 'research',
 'line',
 'economy',
 'histogram',
 'meiosis',
 'escape',
 'noise',
 'finance',
 'medicine',
 'a',
 'travel',
 'snow',
 'experience',
 'sublimation',
 'reality',
 'understanding',
 'ecology',
 'population',
 'arteria',
 'maths',
 'curve',
 'sky',
 'disease',
 'media',
 'collision',
 'movement',
 'organic',
 'temporal',
 'behaviour',
 'river',
 'withdraw',
 'calculate',
 'parasite',
 'mass',
 'eigenvector',
 'maximum',
 'measure',
 'classroom',
 'feature',
 'grade',
 'test',
 'demonstrate',
 'formation',
 'experimenting',
 'machine',
 'laptop',
 'advisor',
 'mentor',
 'phd',
 'authority',
 'space',
 'premise',
 'exam',
 'automata',
 'tree',
 'muscle',
 'class',
 'message',
 'waste',
 'limit',
 'conjecture',
 'median',
 'player',
 'run',
 'condensation',
 'ice',
 'small-world',
 'fungus',
 'order',
 'range',
 'room',
 'coffee',
 'linear',
 'law',
 'obtain',
 'time',
 'promote',
 'programme',
 'simulate',
 'division',
 'produce',
 'activities',
 'proton',
 'constellation',
 'electromagnetism',
 'lens',
 'microscope',
 'researcher',
 'tv',
 'agent',
 'notes',
 'estimator',
 'quantum',
 'rain',
 'flock',
 'synapsis',
 'current']

In [62]:
students_df_unfiltered, cue_words_students_unfiltered = cue_word_extraction(f'{rassereno_path}/data/data_2021/Students_unFiltered.txt')

In [63]:
students_df_filtered, cue_words_students_filtered = cue_word_extraction(f'{rassereno_path}/data/data_2021/Students_Filtered.txt')

In [17]:
list(set(associations_valence_liceo_2025['cue_word']) & set(all_universities_associations_valence['cue_word']) & set(gpt_4o_associations_valence['cue_word']) & set(cue_words_students_unfiltered))

['esame', 'scienziato', 'matematica', 'fisica']

## Check if valences are for filtered or unfiltered df

In [28]:
# counts how many valence ratings per word exist in ValenceStudentsUPD.txt
counts = {}
with open("/Users/emma/Desktop/data_2021/ValenceStudentsUPD.txt", "r") as f:
    for line in f:
        parts = line.strip().split()
        # gets the first element of each row, which is the word
        word = parts[0]
        # gets all the numbers after the word, removing the .
        numbers = [p for p in parts[1:] if p.replace('.', '').isdigit()]
        # counts how many valence ratings per word exist
        counts[word] = counts.get(word, 0) + len(numbers)
df_counts = pd.DataFrame(list(counts.items()), columns=['word', 'count_valence'], index=None)

In [31]:
def count_students_valence(df, file_name):
    combined_counts = (
        df['association_0'].value_counts()
        .add(df['association_1'].value_counts(), fill_value=0)
        .astype(int)
    )

    combined_counts = pd.DataFrame(list(combined_counts.items()), columns=['word', 'count_cue_ass_word'], index=None)

    df = pd.merge(df_counts, combined_counts, on='word', how='outer')
    df.to_csv(f'/Users/emma/projects/cognoscolab/rassereno/out/formatting/students_2021/combined_counts_{file_name}.csv', index=False)

In [32]:
count_students_valence(students_df_unfiltered, 'unfiltered')
count_students_valence(students_df_filtered, 'filtered')

## Creation df for word and associations

In [23]:
# Assign valences sequentially
def assign_valence(row, col_name, valence_map):
    word = row[col_name]
    if word in valence_map and len(valence_map[word]) > 0:
        return float(valence_map[word].pop(0).replace('.', ''))
    else:
        return np.nan

In [48]:
def association_valence_df(input, df, output):
    valences = open(f"/Users/emma/Desktop/data_2021/{input}.txt", "r").readlines()
    valences = [v.strip().split('\t') for v in valences]

    valence_map = {}
    for row in valences:
        if not row[0].replace('.', '').isdigit():
            word = row[0]
            vals = [v for v in row[1:] if v.replace('.', '').isdigit()]
            valence_map.setdefault(word, []).extend(vals)

    df['valence_association_1'] = df.apply(assign_valence, axis=1, args=(('association_1', valence_map)))
    df['valence_association_0'] = df.apply(assign_valence, axis=1, args=(('association_0', valence_map)))

    # df = df['association_0', 'valence_association_0', 'association_1', 'valence_association_1']

    df['new_index'] = df.index + 1
    df['cue_word_original'] = df['association_0']

    # melt from wide to long
    df_long = pd.wide_to_long(df, stubnames=['association', 'valence_association'], i=['new_index', 'cue_word_original'], j='index', sep='_', suffix=r'\d+').reset_index()

    # optional: rename columns for clarity
    df_long = df_long.rename(columns={
        'association': 'word',
        'valence_association': 'valence', 
        'cue_word_original': 'cue_word'
    })

    columns_to_clean = ['cue_word', 'word']
    for col in columns_to_clean:
        if col in df_long.columns:
            df_long[col] = (
                df_long[col]
                .astype(str)
                .str.lower()
                .str.replace(r'[\d\W_]+', ' ', regex=True)
                .str.strip()
            )
    df_long = df_long.dropna()

    df_long = df_long[(df_long['word'] != 'nan') & (df_long['word'] != '')]
    df_long.to_csv(f'{rassereno_path}/out/formatting/{output}/associations_valence_{output}.csv', index=False)

    return df_long

In [52]:
students_ass_val_df = association_valence_df('ValenceStudentsUPD', students_df_unfiltered, 'students_2021')
students_ass_val_df

       new_index    cue_word  index         word  valence
0              1       esame      0        esame      2.0
1              1       esame      1         test      5.0
2              2       esame      0        esame      1.0
3              2       esame      1         test      3.0
4              3        test      0         test      5.0
...          ...         ...    ...          ...      ...
23449      11725      piatto      1    cucchiaio      4.0
23451      11726      piatto      1    forchetta      4.0
23452      11727  produzione      0   produzione      4.0
23453      11727  produzione      1  audiometria      5.0
23455      11728  produzione      1      otorino      5.0

[19574 rows x 5 columns]

In [51]:
experts_ass_val_df = association_valence_df('ValenceExperts', experts_df_unfiltered, 'experts_2021')
experts_ass_val_df

      new_index    cue_word  index        word  valence
0             1      island      0      island      3.0
1             1      island      1         sea      3.0
3             2  land rover      1      island      3.0
5             3  land rover      1         sea      5.0
6             4      island      0      island      3.0
...         ...         ...    ...         ...      ...
6361       3181        herb      1     trimmer      3.0
6363       3182        herb      1  vegetables      5.0
6366       3184    collapse      0    collapse      3.0
6367       3184    collapse      1     destroy      2.0
6369       3185    collapse      1      remove      3.0

[4898 rows x 5 columns]